<?xml version="1.0"?>
<package format="3">
	<name>lidar_cluster_tracker</name>
	<version>0.0.1</version>
	<description>LiDAR cluster tracking node.</description>
	<maintainer email="akz@example.com">akz</maintainer>
	<license>Apache-2.0</license>

	<buildtool_depend>ament_cmake</buildtool_depend>
	<depend>rcl</depend>
	<depend>rclc</depend>
	<depend>sensor_msgs</depend>
	<depend>visualization_msgs</depend>

	<export>
		<build_type>ament_cmake</build_type>
	</export>
</package>
